(function(){'use strict';
var d,f="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof f.global&&f.global?f.global:"object"===typeof global&&global&&global.Object===Object?global:this;f.global=h;var aa="object"===typeof f.exportsNamespace&&f.exportsNamespace?f.exportsNamespace:h;f.exportsNamespace=aa;h.Object.freeze(f);var ba={envInfo:f,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.16"};h.Object.freeze(ba);h.Object.freeze(ba.semantics);
var k=h.Math.imul||function(a,b){var c=a&65535,e=b&65535;return c*e+((a>>>16&65535)*e+c*(b>>>16&65535)<<16>>>0)|0},ca=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=h.WeakMap?new h.WeakMap:null;function l(a){return function(b,c){return!(!b||!b.b||b.b.qa!==c||b.b.oa!==a)}}function fa(a){for(var b in a)return b}
function ga(a,b,c){var e=new a.ub(b[c]);if(c<b.length-1){a=a.sa;c+=1;for(var g=e.U,m=0;m<g.length;m++)g[m]=ga(a,b,c)}return e}function ha(a){return void 0===a?"undefined":a.toString()}
function ia(a){switch(typeof a){case "string":return n(ja);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?n(ka):b<<16>>16===b&&1/b!==1/-0?n(la):n(ma):"number"===typeof a?n(na):n(oa);case "boolean":return n(pa);case "undefined":return n(qa);default:return null===a?a.Be():ra(a)?n(sa):a&&a.b?n(a.b):null}}
function ta(a){switch(typeof a){case "string":return ua(p(),a);case "number":return va(wa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.b||null===a?a.k():null===ea?42:xa(a)}}function ya(a,b){var c=h.Object.getPrototypeOf,e=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=e(a,b);if(void 0!==g)return g;a=c(a)}}function za(a,b,c){a=ya(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Aa(a,b,c,e){a=ya(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,e);return}throw new h.TypeError("super has no setter '"+c+"'.");}
var xa=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ta(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.b){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:ta(a)};
function q(){this.Ja=this.ub=void 0;this.oa=this.sa=this.n=null;this.qa=0;this.qb=null;this.Fa="";this.v=this.Ba=this.Ca=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function t(a,b,c){var e=new q;e.n={};e.sa=null;e.qb=a;e.Fa=b;e.v=function(){return!1};e.name=c;e.isPrimitive=!0;e.isInstance=function(){return!1};return e}
function v(a,b,c,e,g,m,r,E){var y=new q,Z=fa(a);r=r||function(a){return!!(a&&a.b&&a.b.n[Z])};E=E||function(a,b){return!!(a&&a.b&&a.b.qa===b&&a.b.oa.n[Z])};y.Ja=m;y.n=e;y.Fa="L"+c+";";y.v=E;y.name=c;y.isInterface=b;y.isRawJSType=!!g;y.isInstance=r;return y}
function Ba(a){function b(a){if("number"===typeof a){this.U=Array(a);for(var b=0;b<a;b++)this.U[b]=g}else this.U=a}var c=new q,e=a.qb,g="longZero"==e?Ca().Aa:e;b.prototype=new w;b.prototype.constructor=b;b.prototype.b=c;var e="["+a.Fa,m=a.oa||a,r=a.qa+1;c.ub=b;c.Ja=Da;c.n={c:1,Cb:1,d:1};c.sa=a;c.oa=m;c.qa=r;c.qb=null;c.Fa=e;c.Ca=void 0;c.Ba=void 0;c.v=void 0;c.name=e;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return m.v(a,r)};return c}
function n(a){if(!a.Ca){var b=new Ea;b.W=a;a.Ca=b}return a.Ca}function Fa(a){a.Ba||(a.Ba=Ba(a));return a.Ba}q.prototype.getFakeInstance=function(){return this===ja?"some string":this===pa?!1:this===ka||this===la||this===ma||this===na||this===oa?0:this===sa?Ca().Aa:this===qa?void 0:{b:this}};q.prototype.getSuperclass=function(){return this.Ja?n(this.Ja):null};q.prototype.getComponentType=function(){return this.sa?n(this.sa):null};
q.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Fa(b);return ga(b,a,0)};var Ga=t(!1,"Z","boolean"),Ha=t(0,"C","char"),Ia=t(0,"B","byte"),Ja=t(0,"S","short"),Ka=t(0,"I","int"),La=t("longZero","J","long"),Ma=t(0,"F","float"),Na=t(0,"D","double");Ga.v=l(Ga);Ha.v=l(Ha);Ia.v=l(Ia);Ja.v=l(Ja);Ka.v=l(Ka);La.v=l(La);Ma.v=l(Ma);Na.v=l(Na);function Oa(){}function w(){}w.prototype=Oa.prototype;Oa.prototype.a=function(){return this};Oa.prototype.i=function(){var a=ia(this).W.name,b=(+(this.k()>>>0)).toString(16);return a+"@"+b};Oa.prototype.k=function(){return xa(this)};Oa.prototype.toString=function(){return this.i()};var Da=v({c:0},!1,"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.b){var c=a.qa||0;return!(c<b)&&(c>b||!a.oa.isPrimitive)}return!1});Oa.prototype.b=Da;
function Pa(){this.Wa=this.Xb=null;this.y=0}Pa.prototype=new w;Pa.prototype.constructor=Pa;Pa.prototype.a=function(){return this};function x(a){0===(134217728&a.y)&&0===(134217728&a.y)&&(a.Xb=h,a.y|=134217728);return a.Xb}function Qa(a){0===(268435456&a.y)&&(a.Wa=x(a).document,a.y|=268435456);return a.Wa}Pa.prototype.b=v({Zb:0},!1,"org.scalajs.dom.package$",{Zb:1,c:1});var Ra=void 0;function z(){Ra||(Ra=(new Pa).a());return Ra}function Sa(){this.R=this.g=null}Sa.prototype=new w;
Sa.prototype.constructor=Sa;Sa.prototype.b=v({dc:0},!1,"presenter.Slides",{dc:1,c:1});function Ea(){this.W=null}Ea.prototype=new w;Ea.prototype.constructor=Ea;Ea.prototype.i=function(){return(this.W.isInterface?"interface ":this.W.isPrimitive?"":"class ")+this.W.name};Ea.prototype.b=v({lc:0},!1,"java.lang.Class",{lc:1,c:1});function Ta(){}Ta.prototype=new w;Ta.prototype.constructor=Ta;function Ua(){}Ua.prototype=Ta.prototype;var Va=v({H:0},!0,"scala.Product",{H:1,j:1});function Wa(){}
Wa.prototype=new w;Wa.prototype.constructor=Wa;Wa.prototype.a=function(){return this};Wa.prototype.b=v({Pc:0},!1,"scala.math.Ordered$",{Pc:1,c:1});var Xa=void 0;function Ya(){this.y=0}Ya.prototype=new w;Ya.prototype.constructor=Ya;
Ya.prototype.a=function(){Za=this;(new $a).a();ab||(ab=(new bb).a());cb||(cb=(new db).a());eb||(eb=(new fb).a());gb();hb();ib||(ib=(new jb).a());kb();lb||(lb=(new mb).a());nb||(nb=(new ob).a());pb||(pb=(new qb).a());rb||(rb=(new sb).a());tb||(tb=(new ub).a());vb||(vb=(new wb).a());xb||(xb=(new yb).a());zb||(zb=(new Ab).a());Bb||(Bb=(new Cb).a());Db||(Db=(new Eb).a());Fb||(Fb=(new Gb).a());Hb||(Hb=(new Ib).a());Xa||(Xa=(new Wa).a());Jb||(Jb=(new Kb).a());Lb||(Lb=(new Mb).a());Nb||(Nb=(new Ob).a());
Pb||(Pb=(new Qb).a());return this};Ya.prototype.b=v({Rc:0},!1,"scala.package$",{Rc:1,c:1});var Za=void 0;function Rb(){}Rb.prototype=new w;Rb.prototype.constructor=Rb;
Rb.prototype.a=function(){Sb=this;Tb||(Tb=(new Ub).a());Vb||(Vb=(new Wb).a());Xb||(Xb=(new Yb).a());Zb||(Zb=(new $b).a());ac||(ac=(new bc).a());cc||(cc=(new dc).a());ec||(ec=(new fc).a());gc||(gc=(new hc).a());ic||(ic=(new jc).a());kc||(kc=(new lc).a());mc||(mc=(new nc).a());oc||(oc=(new pc).a());qc||(qc=(new rc).a());sc||(sc=(new tc).a());return this};Rb.prototype.b=v({Tc:0},!1,"scala.reflect.ClassManifestFactory$",{Tc:1,c:1});var Sb=void 0;function uc(){}uc.prototype=new w;
uc.prototype.constructor=uc;uc.prototype.a=function(){return this};uc.prototype.b=v({Uc:0},!1,"scala.reflect.ManifestFactory$",{Uc:1,c:1});var vc=void 0;function wc(){}wc.prototype=new w;wc.prototype.constructor=wc;wc.prototype.a=function(){xc=this;Sb||(Sb=(new Rb).a());vc||(vc=(new uc).a());return this};wc.prototype.b=v({jd:0},!1,"scala.reflect.package$",{jd:1,c:1});var xc=void 0;function yc(){}yc.prototype=new w;yc.prototype.constructor=yc;yc.prototype.a=function(){(new zc).a();return this};
yc.prototype.b=v({rd:0},!1,"scala.util.control.Breaks",{rd:1,c:1});function Ac(){}Ac.prototype=new w;Ac.prototype.constructor=Ac;Ac.prototype.a=function(){return this};function Bc(a){return a&&a.b&&a.b.n.Ge||a&&a.b&&a.b.n.Fe||a&&a.b&&a.b.n.De||a&&a.b&&a.b.n.Ee||a&&a.b&&a.b.n.sd?Cc():(new Dc).wa(a)}Ac.prototype.b=v({ud:0},!1,"scala.util.control.NonFatal$",{ud:1,c:1});var Ec=void 0;function Fc(){}Fc.prototype=new w;Fc.prototype.constructor=Fc;function Gc(){}Gc.prototype=Fc.prototype;
Fc.prototype.ab=function(a,b){b=k(-862048943,b);b=k(461845907,b<<15|b>>>17|0);return a^b};Fc.prototype.M=function(a,b){a=this.ab(a,b);return-430675100+k(5,a<<13|a>>>19|0)|0};function Hc(a){var b=Ic(),c=a.E();if(0===c)return a=a.G(),ua(p(),a);for(var e=-889275714,g=0;g<c;)e=b.M(e,Jc(A(),a.F(g))),g=1+g|0;return b.ha(e,c)}Fc.prototype.ha=function(a,b){a^=b;a=k(-2048144789,a^(a>>>16|0));a=k(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};
function Kc(a,b,c){var e=(new B).ua(0);c=(new B).ua(c);b.X(Lc(function(a,b,c){return function(e){c.q=a.M(c.q,Jc(A(),e));b.q=1+b.q|0}}(a,e,c)));return a.ha(c.q,e.q)}function qb(){}qb.prototype=new w;qb.prototype.constructor=qb;qb.prototype.a=function(){return this};qb.prototype.b=v({wd:0},!1,"scala.collection.$colon$plus$",{wd:1,c:1});var pb=void 0;function ob(){}ob.prototype=new w;ob.prototype.constructor=ob;ob.prototype.a=function(){return this};
ob.prototype.b=v({xd:0},!1,"scala.collection.$plus$colon$",{xd:1,c:1});var nb=void 0;function Mc(){this.Xa=null}Mc.prototype=new w;Mc.prototype.constructor=Mc;Mc.prototype.a=function(){Nc=this;this.Xa=(new C).a();return this};Mc.prototype.b=v({Dd:0},!1,"scala.collection.Iterator$",{Dd:1,c:1});var Nc=void 0;function hb(){Nc||(Nc=(new Mc).a());return Nc}function Oc(a,b,c,e){return a.Ua((new Pc).a(),b,c,e).x.o}
function Qc(a,b,c,e,g){var m=Rc();D(b.x,c);a.X(Lc(function(a,b,c,e){return function(a){if(e.q)Sc(b,a),e.q=!1;else return D(b.x,c),Sc(b,a)}}(a,b,e,m)));D(b.x,g);return b}function Tc(){}Tc.prototype=new w;Tc.prototype.constructor=Tc;function Uc(){}Uc.prototype=Tc.prototype;function Vc(){}Vc.prototype=new w;Vc.prototype.constructor=Vc;function Wc(){}Wc.prototype=Vc.prototype;function ub(){}ub.prototype=new w;ub.prototype.constructor=ub;ub.prototype.a=function(){return this};
ub.prototype.b=v({Wd:0},!1,"scala.collection.immutable.Stream$$hash$colon$colon$",{Wd:1,c:1});var tb=void 0;function Xc(){}Xc.prototype=new w;Xc.prototype.constructor=Xc;Xc.prototype.a=function(){return this};function Yc(a,b,c){return 1>=c||1>=(b.length|0)?"":b.substring(1,c>(b.length|0)?b.length|0:c)}Xc.prototype.b=v({Zd:0},!1,"scala.collection.immutable.StringOps$",{Zd:1,c:1});var Zc=void 0;function $c(){Zc||(Zc=(new Xc).a());return Zc}
function ad(){this.ba=!1;this.wb=this.Ia=this.pa=null;this.Va=!1;this.Db=this.Ab=0}ad.prototype=new w;ad.prototype.constructor=ad;
ad.prototype.a=function(){bd=this;this.pa=(this.ba=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.Ia=this.ba?new h.Int32Array(this.pa,0,2):null;this.ba&&new h.Float32Array(this.pa,0,2);this.wb=this.ba?new h.Float64Array(this.pa,0,1):null;if(this.ba)this.Ia[0]=16909060,a=1===((new h.Int8Array(this.pa,0,8))[0]|0);else var a=!0;this.Ab=(this.Va=a)?0:1;this.Db=this.Va?1:0;return this};
function va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.ba)a.wb[0]=b,a=(new F).va(a.Ia[a.Db]|0,a.Ia[a.Ab]|0);else{if(b!==b)a=!1,b=2047,c=+h.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var e=(a=0>b)?-b:b;if(e>=+h.Math.pow(2,-1022)){b=+h.Math.pow(2,52);var c=+h.Math.log(e)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,g=+h.Math.pow(2,c);g>e&&(c=-1+c|0,g/=2);g=e/g*b;e=+h.Math.floor(g);g-=e;e=.5>g?e:.5<g?1+e:0!==e%
2?1+e:e;2<=e/b&&(c=1+c|0,e=1);1023<c?(c=2047,e=0):(c=1023+c|0,e-=b);b=c;c=e}else b=e/+h.Math.pow(2,-1074),c=+h.Math.floor(b),e=b-c,b=0,c=.5>e?c:.5<e?1+c:0!==c%2?1+c:c}c=+c;a=(new F).va(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.la^a.ia}ad.prototype.b=v({oe:0},!1,"scala.scalajs.runtime.Bits$",{oe:1,c:1});var bd=void 0;function wa(){bd||(bd=(new ad).a());return bd}function cd(){this.y=!1}cd.prototype=new w;cd.prototype.constructor=cd;cd.prototype.a=function(){return this};
function dd(){return h.String.fromCharCode(92)}function ua(a,b){a=0;for(var c=1,e=-1+(b.length|0)|0;0<=e;)a=a+k(65535&(b.charCodeAt(e)|0),c)|0,c=k(31,c),e=-1+e|0;return a}cd.prototype.b=v({qe:0},!1,"scala.scalajs.runtime.RuntimeString$",{qe:1,c:1});var ed=void 0;function p(){ed||(ed=(new cd).a());return ed}function fd(){}fd.prototype=new w;fd.prototype.constructor=fd;fd.prototype.a=function(){return this};function gd(a,b){return b&&b.b&&b.b.n.nb?b.ga:b}
function hd(a,b){return b&&b.b&&b.b.n.L?b:(new id).wa(b)}fd.prototype.b=v({re:0},!1,"scala.scalajs.runtime.package$",{re:1,c:1});var jd=void 0;function kd(){jd||(jd=(new fd).a());return jd}var ld=v({we:0},!1,"scala.runtime.Null$",{we:1,c:1});function md(){}md.prototype=new w;md.prototype.constructor=md;md.prototype.a=function(){return this};function nd(a){od||(od=(new md).a());var b=a.N();return Oc(b,a.G()+"(",",",")")}md.prototype.b=v({xe:0},!1,"scala.runtime.ScalaRunTime$",{xe:1,c:1});var od=void 0;
function pd(){}pd.prototype=new w;pd.prototype.constructor=pd;d=pd.prototype;d.a=function(){return this};d.ab=function(a,b){b=k(-862048943,b);b=k(461845907,b<<15|b>>>17|0);return a^b};
function Jc(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=Ca();var c;if(-9223372036854775808>a)b.Ma=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.Ma=2147483647,c=-1;else{c=a|0;var e=a/4294967296|0;b.Ma=0>a&&0!==c?-1+e|0:e}b=b.Ma;Ca();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:va(wa(),a)}return a}return ra(b)?(a=null===b?Ca().Aa:b,b=(new F).va(a.la,a.ia),a=b.la,b=b.ia,
b===a>>31?a:a^b):ta(b)}d.M=function(a,b){a=this.ab(a,b);return-430675100+k(5,a<<13|a>>>19|0)|0};d.ha=function(a,b){a^=b;a=k(-2048144789,a^(a>>>16|0));a=k(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};d.b=v({ze:0},!1,"scala.runtime.Statics$",{ze:1,c:1});var qd=void 0;function A(){qd||(qd=(new pd).a());return qd}function rd(){this.Sa=this.w=this.Ta=null;this.Pa=this.Qa=0;this.R=this.Vb=null;this.z=0}rd.prototype=new w;rd.prototype.constructor=rd;
rd.prototype.a=function(){sd=this;var a=z();this.Ta=(0===(268435456&a.y)?Qa(a):a.Wa).getElementById("svg-object");this.w=this.Ta.contentDocument;this.Sa=this.w.getElementById("svg2");this.Qa=1024;this.Pa=768;a=new Sa;a.g=this.w;for(var b=G(new H,[(new I).e("TITLE"),(new I).e("WELCOME"),(new I).e("ME"),(new I).e("GOAL"),(new I).e("MOTIVATION"),(new I).e("FALLACIES"),(new I).e("APPROACH"),(new I).e("DISCLAIMER"),(new I).e("PAST"),(new I).e("ARROW"),(new I).e("PASTPRESENT"),(new I).e("UI"),(new J).h("UI-0",
"UI-1",1,a.g),(new J).h("UI-1","UI-2",2,a.g),(new J).h("UI-2","UI-3",3,a.g),(new J).h("UI-3","UI-4",4,a.g),(new J).h("UI-4","UI-5",5,a.g),(new I).e("PASTPRESENT"),(new I).e("FP"),(new J).h("FP-0","FP-1",1,a.g),(new J).h("FP-1","FP-2",2,a.g),(new J).h("FP-2","FP-3",3,a.g),(new J).h("FP-3","FP-4",4,a.g),(new J).h("FP-4","FP-5",5,a.g),(new I).e("PASTPRESENT"),(new I).e("OL"),(new K).h("OL-0","OL-1",1,a.g),(new K).h("OL-1","OL-2",2,a.g),(new K).h("OL-2","OL-3",3,a.g),(new K).h("OL-3","OL-4",4,a.g),(new I).e("PASTARROW"),
(new I).e("FC"),(new K).h("FC-0","FC-1",1,a.g),(new K).h("FC-1","FC-2",2,a.g),(new I).e("PRESENT"),(new I).e("PASTPRESENT"),(new I).e("PS"),(new J).h("PS-0","PS-1",1,a.g),(new J).h("PS-1","PS-2",2,a.g),(new J).h("PS-2","PS-3",3,a.g),(new J).h("PS-3","PS-4",4,a.g),(new J).h("PS-4","PS-5",5,a.g),(new J).h("PS-5","PS-6",6,a.g),(new I).e("PASTPRESENT"),(new I).e("VB"),(new K).h("VB-0","VB-1",1,a.g),(new K).h("VB-1","VB-2",2,a.g),(new K).h("VB-2","VB-3",3,a.g),(new K).h("VB-3","VB-4",4,a.g),(new K).h("VB-4",
"VB-5",5,a.g),(new I).e("FUTURE"),(new I).e("TP"),(new K).h("TP-0","TP-1",1,a.g),(new K).h("TP-1","TP-2",2,a.g),(new K).h("TP-2","TP-3",3,a.g),(new I).e("LI"),(new K).h("LI-0","LI-1",1,a.g),(new K).h("LI-1","LI-2",2,a.g),(new I).e("EN"),(new K).h("EN-0","EN-1",1,a.g),(new K).h("EN-1","EN-2",2,a.g),(new I).e("DI"),(new K).h("DI-0","DI-1",1,a.g),(new K).h("DI-1","DI-2",2,a.g),(new K).h("DI-2","DI-3",3,a.g),(new I).e("AV"),(new K).h("AV-0","AV-1",1,a.g),(new K).h("AV-1","AV-2",2,a.g),(new K).h("AV-2",
"AV-3",3,a.g),(new I).e("MO"),(new I).e("CONCLUSION"),(new I).e("THANKS"),(new I).e("QUESTIONS"),(new I).e("END"),(new I).e("ARROW")]),c=b.V.length|0,e=Fa(Va),c=ga(e,[c],0),e=0,b=td(b,b.V.length|0);b.O();){var g=b.C();c.U[e]=g;e=1+e|0}a.R=c;this.Vb=a;this.R=this.Vb.R;this.z=0;return this};
function ud(a){var b=h.URLSearchParams,c=x(z()).location.search,c=(new L).e(c),e=c.m.length|0,c=Yc($c(),c.m,e),b=new b(c),c=b.get("width");null!==c&&(c=(new L).e(c),a.Qa=vd(wd(),c.m));b=b.get("height");null!==b&&(b=(new L).e(b),a.Pa=vd(wd(),b.m));a.Ta.setAttribute("width",M(N(new O,G(new H,["",""])),G(new H,[a.Qa])));a.Ta.setAttribute("height",M(N(new O,G(new H,["",""])),G(new H,[a.Pa])));a.Sa.onmousedown=function(a){var b=xd();0===(a.button|0)?yd(b):2===(a.button|0)&&(b.z=1>b.z?-1+b.R.U.length|0:
-1+b.z|0,b.R.U[-1+b.z|0].Da());x(z()).history.pushState(null,null,M(N(new O,G(new H,["#",""])),G(new H,[b.z])));return!1};x(z()).oncontextmenu=function(){xd();return!1};try{var g=x(z()).location.hash,m=(new L).e(g),r=m.m.length|0,E=Yc($c(),m.m,r),y=(new L).e(E);wd();var Z=(new zd).wa(vd(0,y.m))}catch(u){if(g=hd(kd(),u),null!==g){Ec||(Ec=(new Ac).a());m=Bc(g);if(m.P())throw gd(kd(),g);g=m.zb();Z=Ad(g)}else throw u;}for(g=Z.yb(Bd(function(){return function(){return 0}}(a)))|0;0<g;)yd(a),g=-1+g|0}
function yd(a){a.R.U[a.z].Da();a.z=1+a.z|0;a.z>=a.R.U.length&&(a.z=0)}rd.prototype.main=function(){ud(this)};rd.prototype.b=v({cc:0},!1,"presenter.Presentation$",{cc:1,c:1,of:1});var sd=void 0;function xd(){sd||(sd=(new rd).a());return sd}function Cd(){}Cd.prototype=new w;Cd.prototype.constructor=Cd;function Dd(){}Dd.prototype=Cd.prototype;function P(){this.r=null}P.prototype=new w;P.prototype.constructor=P;function Ed(){}Ed.prototype=P.prototype;
P.prototype.Ga=function(){if(void 0===h.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=hd(kd(),b),null!==a)if(a&&a.b&&a.b.n.nb)a=a.ga;else throw gd(kd(),a);else throw b;}this.stackdata=a}else h.Error.captureStackTrace(this),this.stackdata=this;return this};P.prototype.xb=function(){return this.r};P.prototype.i=function(){var a=ia(this).W.name,b=this.xb();return null===b?a:a+": "+b};P.prototype.K=function(a){this.r=a;this.Ga();return this};function Fd(){}Fd.prototype=new w;
Fd.prototype.constructor=Fd;Fd.prototype.a=function(){return this};Fd.prototype.b=v({Fc:0},!1,"scala.Predef$$anon$3",{Fc:1,c:1,Sb:1});function $a(){}$a.prototype=new w;$a.prototype.constructor=$a;$a.prototype.a=function(){return this};$a.prototype.i=function(){return"object AnyRef"};$a.prototype.b=v({Sc:0},!1,"scala.package$$anon$1",{Sc:1,c:1,Me:1});function Gd(){this.mb=0}Gd.prototype=new Gc;Gd.prototype.constructor=Gd;
Gd.prototype.a=function(){Hd=this;this.mb=ua(p(),"Seq");ua(p(),"Map");ua(p(),"Set");return this};function Id(a){var b=Ic();if(a&&a.b&&a.b.n.Od){for(var c=0,e=b.mb;!a.P();)Jd(),a=Kd(),e=b.M(e,Jc(A(),void 0)),c=1+c|0;b=b.ha(e,c)}else b=Kc(b,a,b.mb);return b}Gd.prototype.b=v({vd:0},!1,"scala.util.hashing.MurmurHash3$",{vd:1,Qe:1,c:1});var Hd=void 0;function Ic(){Hd||(Hd=(new Gd).a());return Hd}function Ld(){}Ld.prototype=new Wc;Ld.prototype.constructor=Ld;function Md(){}Md.prototype=Ld.prototype;
function Q(){}Q.prototype=new Wc;Q.prototype.constructor=Q;function Nd(){}Nd.prototype=Q.prototype;Q.prototype.a=function(){(new Od).Ha(this);return this};function Pd(){}Pd.prototype=new w;Pd.prototype.constructor=Pd;function Qd(){}Qd.prototype=Pd.prototype;Pd.prototype.Ha=function(a){if(null===a)throw gd(kd(),null);return this};function Rd(){}Rd.prototype=new Uc;Rd.prototype.constructor=Rd;function Sd(){}Sd.prototype=Rd.prototype;function R(){}R.prototype=new w;R.prototype.constructor=R;
R.prototype.a=function(){return this};R.prototype.J=function(){return this};R.prototype.i=function(){return"\x3cfunction1\x3e"};R.prototype.b=v({Qd:0},!1,"scala.collection.immutable.List$$anon$1",{Qd:1,c:1,fa:1});function Td(){}Td.prototype=new w;Td.prototype.constructor=Td;function Ud(){}Ud.prototype=Td.prototype;Td.prototype.i=function(){return"\x3cfunction0\x3e"};function Vd(){}Vd.prototype=new w;Vd.prototype.constructor=Vd;function Wd(){}Wd.prototype=Vd.prototype;Vd.prototype.i=function(){return"\x3cfunction1\x3e"};
function Xd(){this.q=!1}Xd.prototype=new w;Xd.prototype.constructor=Xd;Xd.prototype.i=function(){return""+this.q};function Rc(){var a=new Xd;a.q=!0;return a}Xd.prototype.b=v({se:0},!1,"scala.runtime.BooleanRef",{se:1,c:1,d:1});var qa=v({te:0},!1,"scala.runtime.BoxedUnit",{te:1,c:1,d:1},void 0,void 0,function(a){return void 0===a});function B(){this.q=0}B.prototype=new w;B.prototype.constructor=B;B.prototype.i=function(){return""+this.q};B.prototype.ua=function(a){this.q=a;return this};
B.prototype.b=v({ue:0},!1,"scala.runtime.IntRef",{ue:1,c:1,d:1});var pa=v({hc:0},!1,"java.lang.Boolean",{hc:1,c:1,d:1,A:1},void 0,void 0,function(a){return"boolean"===typeof a});function Yd(){this.pb=0}Yd.prototype=new w;Yd.prototype.constructor=Yd;Yd.prototype.i=function(){return h.String.fromCharCode(this.pb)};function Zd(a){var b=new Yd;b.pb=a;return b}Yd.prototype.k=function(){return this.pb};Yd.prototype.b=v({jc:0},!1,"java.lang.Character",{jc:1,c:1,d:1,A:1});function $d(){this.y=0}
$d.prototype=new w;$d.prototype.constructor=$d;$d.prototype.a=function(){return this};$d.prototype.b=v({kc:0},!1,"java.lang.Character$",{kc:1,c:1,f:1,d:1});var ae=void 0;function be(){this.r=null}be.prototype=new Ed;be.prototype.constructor=be;function ce(){}ce.prototype=be.prototype;function de(){}de.prototype=new w;de.prototype.constructor=de;de.prototype.a=function(){return this};function ee(a){throw(new fe).e(M(N(new O,G(new H,['For input string: "','"'])),G(new H,[a])));}
function vd(a,b){if(null===b||0===((new L).e(b).m.length|0))ee(b);else if(a=45===(65535&(b.charCodeAt(0)|0))||43===(65535&(b.charCodeAt(0)|0))?1:0,((new L).e(b).m.length|0)<=a)ee(b);else{for(;;){var c=a,e=(new L).e(b).m;if(c<(e.length|0))ae||(ae=(new $d).a()),c=65535&(b.charCodeAt(a)|0),0>(48<=c&&57>=c&&10>(-48+c|0)?-48+c|0:65<=c&&90>=c&&0>(-65+c|0)?-55+c|0:97<=c&&122>=c&&0>(-97+c|0)?-87+c|0:65313<=c&&65338>=c&&0>(-65313+c|0)?-65303+c|0:65345<=c&&65370>=c&&0>(-65345+c|0)?-65303+c|0:-1)&&ee(b),a=1+
a|0;else break}a=+h.parseInt(b,10);return a!==a||2147483647<a||-2147483648>a?ee(b):2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}}de.prototype.b=v({qc:0},!1,"java.lang.Integer$",{qc:1,c:1,f:1,d:1});var ge=void 0;function wd(){ge||(ge=(new de).a());return ge}function he(){}he.prototype=new Ua;he.prototype.constructor=he;
he.prototype.a=function(){ie=this;Za||(Za=(new Ya).a());ib||(ib=(new jb).a());je||(je=(new ke).a());le||(le=(new me).a());xc||(xc=(new wc).a());xc||(xc=(new wc).a());ne||(ne=(new oe).a());(new Fd).a();(new pe).a();(new qe).a();return this};he.prototype.b=v({Cc:0},!1,"scala.Predef$",{Cc:1,Je:1,c:1,He:1});var ie=void 0;function re(){}re.prototype=new w;re.prototype.constructor=re;re.prototype.a=function(){return this};re.prototype.b=v({Ic:0},!1,"scala.StringContext$",{Ic:1,c:1,f:1,d:1});var se=void 0;
function Eb(){}Eb.prototype=new w;Eb.prototype.constructor=Eb;Eb.prototype.a=function(){return this};Eb.prototype.b=v({Lc:0},!1,"scala.math.Fractional$",{Lc:1,c:1,f:1,d:1});var Db=void 0;function Gb(){}Gb.prototype=new w;Gb.prototype.constructor=Gb;Gb.prototype.a=function(){return this};Gb.prototype.b=v({Mc:0},!1,"scala.math.Integral$",{Mc:1,c:1,f:1,d:1});var Fb=void 0;function Ib(){}Ib.prototype=new w;Ib.prototype.constructor=Ib;Ib.prototype.a=function(){return this};
Ib.prototype.b=v({Nc:0},!1,"scala.math.Numeric$",{Nc:1,c:1,f:1,d:1});var Hb=void 0;function Mb(){}Mb.prototype=new w;Mb.prototype.constructor=Mb;Mb.prototype.a=function(){return this};Mb.prototype.b=v({kd:0},!1,"scala.util.Either$",{kd:1,c:1,f:1,d:1});var Lb=void 0;function Ob(){}Ob.prototype=new w;Ob.prototype.constructor=Ob;Ob.prototype.a=function(){return this};Ob.prototype.i=function(){return"Left"};Ob.prototype.b=v({md:0},!1,"scala.util.Left$",{md:1,c:1,f:1,d:1});var Nb=void 0;
function Qb(){}Qb.prototype=new w;Qb.prototype.constructor=Qb;Qb.prototype.a=function(){return this};Qb.prototype.i=function(){return"Right"};Qb.prototype.b=v({nd:0},!1,"scala.util.Right$",{nd:1,c:1,f:1,d:1});var Pb=void 0;function te(){this.rb=!1}te.prototype=new w;te.prototype.constructor=te;te.prototype.a=function(){this.rb=!1;return this};te.prototype.b=v({td:0},!1,"scala.util.control.NoStackTrace$",{td:1,c:1,f:1,d:1});var ue=void 0;function ve(){}ve.prototype=new Qd;
ve.prototype.constructor=ve;ve.prototype.a=function(){Pd.prototype.Ha.call(this,gb());return this};ve.prototype.b=v({Ad:0},!1,"scala.collection.IndexedSeq$$anon$1",{Ad:1,Kd:1,c:1,Sb:1});function we(){}we.prototype=new Nd;we.prototype.constructor=we;function xe(){}xe.prototype=we.prototype;function Od(){this.za=null}Od.prototype=new Qd;Od.prototype.constructor=Od;Od.prototype.Ha=function(a){if(null===a)throw gd(kd(),null);this.za=a;Pd.prototype.Ha.call(this,a);return this};
Od.prototype.b=v({Jd:0},!1,"scala.collection.generic.GenTraversableFactory$$anon$1",{Jd:1,Kd:1,c:1,Sb:1});function ye(){}ye.prototype=new Sd;ye.prototype.constructor=ye;function ze(){}ze.prototype=ye.prototype;function mb(){}mb.prototype=new w;mb.prototype.constructor=mb;mb.prototype.a=function(){return this};mb.prototype.i=function(){return"::"};mb.prototype.b=v({Nd:0},!1,"scala.collection.immutable.$colon$colon$",{Nd:1,c:1,f:1,d:1});var lb=void 0;function Ab(){}Ab.prototype=new w;
Ab.prototype.constructor=Ab;Ab.prototype.a=function(){return this};Ab.prototype.b=v({Td:0},!1,"scala.collection.immutable.Range$",{Td:1,c:1,f:1,d:1});var zb=void 0;function yb(){}yb.prototype=new w;yb.prototype.constructor=yb;yb.prototype.a=function(){return this};yb.prototype.b=v({je:0},!1,"scala.collection.mutable.StringBuilder$",{je:1,c:1,f:1,d:1});var xb=void 0;function Ae(){this.ta=null}Ae.prototype=new Ud;Ae.prototype.constructor=Ae;function Bd(a){var b=new Ae;b.ta=a;return b}
Ae.prototype.b=v({me:0},!1,"scala.scalajs.runtime.AnonFunction0",{me:1,pf:1,c:1,Ae:1});function Be(){this.ta=null}Be.prototype=new Wd;Be.prototype.constructor=Be;Be.prototype.J=function(a){return(0,this.ta)(a)};function Lc(a){var b=new Be;b.ta=a;return b}Be.prototype.b=v({ne:0},!1,"scala.scalajs.runtime.AnonFunction1",{ne:1,qf:1,c:1,fa:1});function Ce(){this.Ma=0;this.Aa=null}Ce.prototype=new w;Ce.prototype.constructor=Ce;Ce.prototype.a=function(){De=this;this.Aa=(new F).va(0,0);return this};
function Ee(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,e=c,g=0===(32&e)?1E9<<e:0,e=0===(32&e)?5E8>>>(31-e|0)|0|0<<e:1E9<<e,m=a,r=b;for(a=b=0;0<=c&&0!==(-2097152&r);){var E=m,y=r,Z=g,u=e;if(y===u?(-2147483648^E)>=(-2147483648^Z):(-2147483648^y)>=(-2147483648^u))E=r,y=e,r=m-g|0,E=(-2147483648^r)>(-2147483648^m)?-1+(E-y|0)|0:E-y|0,m=r,r=E,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;E=e>>>1|0;g=g>>>1|0|e<<31;e=E}c=r;if(0===c?-1147483648<=(-2147483648^
m):-2147483648<=(-2147483648^c))c=4294967296*r+ +(m>>>0),m=c/1E9,g=m/4294967296|0,e=b,b=m=e+(m|0)|0,a=(-2147483648^m)<(-2147483648^e)?1+(a+g|0)|0:a+g|0,m=c%1E9|0;c=""+m;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}Ce.prototype.b=v({pe:0},!1,"scala.scalajs.runtime.RuntimeLong$",{pe:1,c:1,f:1,d:1});var De=void 0;function Ca(){De||(De=(new Ce).a());return De}
var Fe=v({ve:0},!1,"scala.runtime.Nothing$",{ve:1,L:1,c:1,d:1}),ja=v({ec:0},!1,"java.lang.String",{ec:1,c:1,d:1,Bb:1,A:1},void 0,void 0,function(a){return"string"===typeof a}),ka=v({ic:0},!1,"java.lang.Byte",{ic:1,ka:1,c:1,d:1,A:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),oa=v({mc:0},!1,"java.lang.Double",{mc:1,ka:1,c:1,d:1,A:1},void 0,void 0,function(a){return"number"===typeof a}),na=v({nc:0},!1,"java.lang.Float",{nc:1,ka:1,c:1,d:1,A:1},void 0,void 0,function(a){return"number"===
typeof a}),ma=v({pc:0},!1,"java.lang.Integer",{pc:1,ka:1,c:1,d:1,A:1},void 0,void 0,function(a){return(a|0)===a&&1/a!==1/-0}),sa=v({rc:0},!1,"java.lang.Long",{rc:1,ka:1,c:1,d:1,A:1},void 0,void 0,function(a){return ra(a)});function Ge(){this.r=null}Ge.prototype=new ce;Ge.prototype.constructor=Ge;function He(){}He.prototype=Ge.prototype;var la=v({uc:0},!1,"java.lang.Short",{uc:1,ka:1,c:1,d:1,A:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function S(){this.o=null}S.prototype=new w;
S.prototype.constructor=S;d=S.prototype;d.a=function(){S.prototype.e.call(this,"");return this};function D(a,b){a.o=""+a.o+(null===b?"null":b);return a}d.Wb=function(a,b){return this.o.substring(a,b)};d.i=function(){return this.o};function Ie(a,b){null===b?D(a,null):D(a,ha(b))}d.ua=function(){S.prototype.e.call(this,"");return this};function Je(a,b,c,e){null===b?a=Je(a,"null",c,e):(b="string"===typeof b?b.substring(c,e):b.Wb(c,e),a=D(a,ha(b)));return a}d.e=function(a){this.o=a;return this};
d.b=v({vc:0},!1,"java.lang.StringBuilder",{vc:1,c:1,Bb:1,Ce:1,d:1});function Ke(){}Ke.prototype=new w;Ke.prototype.constructor=Ke;function Le(){}Le.prototype=Ke.prototype;Ke.prototype.i=function(){return"\x3cfunction1\x3e"};function Me(){}Me.prototype=new w;Me.prototype.constructor=Me;function Ne(){}Ne.prototype=Me.prototype;Me.prototype.i=function(){return"\x3cfunction1\x3e"};function Cb(){}Cb.prototype=new w;Cb.prototype.constructor=Cb;Cb.prototype.a=function(){return this};
Cb.prototype.b=v({Kc:0},!1,"scala.math.Equiv$",{Kc:1,c:1,Ne:1,f:1,d:1});var Bb=void 0;function Kb(){}Kb.prototype=new w;Kb.prototype.constructor=Kb;Kb.prototype.a=function(){return this};Kb.prototype.b=v({Qc:0},!1,"scala.math.Ordering$",{Qc:1,c:1,Oe:1,f:1,d:1});var Jb=void 0;function oe(){}oe.prototype=new w;oe.prototype.constructor=oe;oe.prototype.a=function(){return this};oe.prototype.i=function(){return"\x3c?\x3e"};oe.prototype.b=v({id:0},!1,"scala.reflect.NoManifest$",{id:1,c:1,p:1,f:1,d:1});
var ne=void 0;function Oe(){}Oe.prototype=new w;Oe.prototype.constructor=Oe;function Pe(){}Pe.prototype=Oe.prototype;Oe.prototype.i=function(){return(this.O()?"non-empty":"empty")+" iterator"};Oe.prototype.X=function(a){for(;this.O();)a.J(this.C())};Oe.prototype.Ua=function(a,b,c,e){return Qc(this,a,b,c,e)};function Qe(){}Qe.prototype=new Md;Qe.prototype.constructor=Qe;function Re(){}Re.prototype=Qe.prototype;function ke(){}ke.prototype=new ze;ke.prototype.constructor=ke;ke.prototype.a=function(){return this};
ke.prototype.b=v({Rd:0},!1,"scala.collection.immutable.Map$",{Rd:1,Ye:1,$e:1,We:1,c:1});var je=void 0;function F(){this.ia=this.la=0}F.prototype=new Dd;F.prototype.constructor=F;d=F.prototype;d.i=function(){Ca();var a=this.la,b=this.ia;return b===a>>31?""+a:0>b?"-"+Ee(-a|0,0!==a?~b:-b|0):Ee(a,b)};d.va=function(a,b){this.la=a;this.ia=b;return this};d.ua=function(a){F.prototype.va.call(this,a,a>>31);return this};d.k=function(){return this.la^this.ia};function ra(a){return!!(a&&a.b&&a.b.n.Ub)}
d.b=v({Ub:0},!1,"scala.scalajs.runtime.RuntimeLong",{Ub:1,ka:1,c:1,d:1,A:1});function T(){this.r=null}T.prototype=new He;T.prototype.constructor=T;function Se(){}Se.prototype=T.prototype;T.prototype.a=function(){P.prototype.K.call(this,null);return this};T.prototype.e=function(a){P.prototype.K.call(this,a);return this};T.prototype.b=v({$a:0},!1,"java.lang.IllegalArgumentException",{$a:1,Z:1,Y:1,L:1,c:1,d:1});function U(){this.r=null}U.prototype=new He;U.prototype.constructor=U;
U.prototype.e=function(a){P.prototype.K.call(this,a);return this};U.prototype.b=v({oc:0},!1,"java.lang.IndexOutOfBoundsException",{oc:1,Z:1,Y:1,L:1,c:1,d:1});function Te(){this.r=null}Te.prototype=new He;Te.prototype.constructor=Te;Te.prototype.a=function(){P.prototype.K.call(this,null);return this};Te.prototype.b=v({sc:0},!1,"java.lang.NullPointerException",{sc:1,Z:1,Y:1,L:1,c:1,d:1});function Ue(){this.r=null}Ue.prototype=new He;Ue.prototype.constructor=Ue;
Ue.prototype.e=function(a){P.prototype.K.call(this,a);return this};Ue.prototype.b=v({wc:0},!1,"java.lang.UnsupportedOperationException",{wc:1,Z:1,Y:1,L:1,c:1,d:1});function V(){this.r=null}V.prototype=new He;V.prototype.constructor=V;V.prototype.e=function(a){P.prototype.K.call(this,a);return this};V.prototype.b=v({xc:0},!1,"java.util.NoSuchElementException",{xc:1,Z:1,Y:1,L:1,c:1,d:1});function Ve(){}Ve.prototype=new w;Ve.prototype.constructor=Ve;function We(){}We.prototype=Ve.prototype;
function pe(){}pe.prototype=new Ne;pe.prototype.constructor=pe;pe.prototype.a=function(){return this};pe.prototype.J=function(a){return a};pe.prototype.b=v({Dc:0},!1,"scala.Predef$$anon$1",{Dc:1,Le:1,c:1,fa:1,f:1,d:1});function qe(){}qe.prototype=new Le;qe.prototype.constructor=qe;qe.prototype.a=function(){return this};qe.prototype.J=function(a){return a};qe.prototype.b=v({Ec:0},!1,"scala.Predef$$anon$2",{Ec:1,Ke:1,c:1,fa:1,f:1,d:1});function O(){this.ya=null}O.prototype=new w;
O.prototype.constructor=O;d=O.prototype;d.G=function(){return"StringContext"};d.E=function(){return 1};d.F=function(a){switch(a){case 0:return this.ya;default:throw(new U).e(""+a);}};d.i=function(){return nd(this)};function Xe(a,b){if(a.ya.S()!==(1+b.S()|0))throw(new T).e("wrong number of arguments ("+b.S()+") for interpolated string with "+a.ya.S()+" parts");}
function M(a,b){var c=function(){return function(a){se||(se=(new re).a());a:{var b=a.length|0,c;p();var e=dd();c=a.indexOf(e)|0;switch(c){case -1:break a;default:e=(new S).a();b:{var g=c;c=0;for(;;)if(0<=g){g>c&&Je(e,a,c,g);c=1+g|0;if(c>=b)throw Ye(a,g);var u=65535&(a.charCodeAt(c)|0);switch(u){case 98:g=8;break;case 116:g=9;break;case 110:g=10;break;case 102:g=12;break;case 114:g=13;break;case 34:g=34;break;case 39:g=39;break;case 92:g=92;break;default:if(48<=u&&55>=u)g=65535&(a.charCodeAt(c)|0),
u=-48+g|0,c=1+c|0,c<b&&48<=(65535&(a.charCodeAt(c)|0))&&55>=(65535&(a.charCodeAt(c)|0))&&(u=-48+((u<<3)+(65535&(a.charCodeAt(c)|0))|0)|0,c=1+c|0,c<b&&51>=g&&48<=(65535&(a.charCodeAt(c)|0))&&55>=(65535&(a.charCodeAt(c)|0))&&(u=-48+((u<<3)+(65535&(a.charCodeAt(c)|0))|0)|0,c=1+c|0)),c=-1+c|0,g=65535&u;else throw Ye(a,g);}c=1+c|0;D(e,h.String.fromCharCode(g));g=c;p();var u=a,vf=dd(),u=u.indexOf(vf,c)|0;c=g;g=u}else{c<b&&Je(e,a,c,b);a=e.o;break b}}}}return a}}(a);Xe(a,b);a=a.ya.xa();b=b.xa();for(var e=
a.C(),e=(new S).e(c(e));b.O();){Ie(e,b.C());var g=a.C();D(e,c(g))}return e.o}function N(a,b){a.ya=b;return a}d.k=function(){return Hc(this)};d.N=function(){return W(this)};d.b=v({Hc:0},!1,"scala.StringContext",{Hc:1,c:1,H:1,j:1,f:1,d:1});function Ze(){}Ze.prototype=new w;Ze.prototype.constructor=Ze;function $e(){}$e.prototype=Ze.prototype;function zc(){this.r=null}zc.prototype=new Ed;zc.prototype.constructor=zc;zc.prototype.a=function(){P.prototype.K.call(this,null);return this};
zc.prototype.Ga=function(){ue||(ue=(new te).a());return ue.rb?P.prototype.Ga.call(this):this};zc.prototype.b=v({qd:0},!1,"scala.util.control.BreakControl",{qd:1,L:1,c:1,d:1,sd:1,Pe:1});function db(){}db.prototype=new Nd;db.prototype.constructor=db;db.prototype.a=function(){Q.prototype.a.call(this);return this};db.prototype.b=v({Cd:0},!1,"scala.collection.Iterable$",{Cd:1,ma:1,ca:1,c:1,na:1,da:1});var cb=void 0;function C(){}C.prototype=new Pe;C.prototype.constructor=C;C.prototype.a=function(){return this};
C.prototype.C=function(){throw(new V).e("next on empty iterator");};C.prototype.O=function(){return!1};C.prototype.b=v({Ed:0},!1,"scala.collection.Iterator$$anon$2",{Ed:1,bb:1,c:1,gb:1,aa:1,$:1});function af(){this.ob=null}af.prototype=new Pe;af.prototype.constructor=af;af.prototype.C=function(){if(this.O())Jd(),this.ob=Kd();else return hb().Xa.C()};af.prototype.O=function(){return!this.ob.P()};af.prototype.b=v({Fd:0},!1,"scala.collection.LinearSeqLike$$anon$1",{Fd:1,bb:1,c:1,gb:1,aa:1,$:1});
function bb(){}bb.prototype=new Nd;bb.prototype.constructor=bb;bb.prototype.a=function(){Q.prototype.a.call(this);ab=this;(new yc).a();return this};bb.prototype.b=v({Hd:0},!1,"scala.collection.Traversable$",{Hd:1,ma:1,ca:1,c:1,na:1,da:1});var ab=void 0;function bf(){}bf.prototype=new Re;bf.prototype.constructor=bf;function cf(){}cf.prototype=bf.prototype;function df(){this.tb=this.ra=0;this.Yb=null}df.prototype=new Pe;df.prototype.constructor=df;
df.prototype.C=function(){var a=this.Yb.F(this.ra);this.ra=1+this.ra|0;return a};function W(a){var b=new df;b.Yb=a;b.ra=0;b.tb=a.E();return b}df.prototype.O=function(){return this.ra<this.tb};df.prototype.b=v({ye:0},!1,"scala.runtime.ScalaRunTime$$anon$1",{ye:1,bb:1,c:1,gb:1,aa:1,$:1});function K(){this.B=this.D=null;this.Q=0;this.w=null}K.prototype=new w;K.prototype.constructor=K;d=K.prototype;d.G=function(){return"FadeAndSlide"};d.E=function(){return 3};
d.h=function(a,b,c,e){this.D=a;this.B=b;this.Q=c;this.w=e;return this};d.Da=function(){var a=this.w.getElementById(this.D);null===a&&x(z()).alert(M(N(new O,G(new H,["no elem with id ","!"])),G(new H,[this.D])));var b=this.w.getElementById(this.B);null===b&&x(z()).alert(M(N(new O,G(new H,["no elem with id ","!"])),G(new H,[this.B])));var c=k(-70,this.Q);a.setAttribute("visibility","hidden");b.setAttribute("transform",M(N(new O,G(new H,[" translate(0,",")"])),G(new H,[c])))};
d.F=function(a){switch(a){case 0:return this.D;case 1:return this.B;case 2:return this.Q;default:throw(new U).e(""+a);}};d.i=function(){return nd(this)};d.k=function(){var a=-889275714,a=A().M(a,Jc(A(),this.D)),a=A().M(a,Jc(A(),this.B)),a=A().M(a,this.Q);return A().ha(a,3)};d.N=function(){return W(this)};d.b=v({$b:0},!1,"presenter.FadeAndSlide",{$b:1,c:1,sb:1,H:1,j:1,f:1,d:1});function J(){this.B=this.D=null;this.Q=0;this.w=null}J.prototype=new w;J.prototype.constructor=J;d=J.prototype;d.G=function(){return"FadeAndSlideDown"};
d.E=function(){return 3};d.h=function(a,b,c,e){this.D=a;this.B=b;this.Q=c;this.w=e;return this};d.Da=function(){var a=this.w.getElementById(this.D);null===a&&x(z()).alert(M(N(new O,G(new H,["no elem with id ","!"])),G(new H,[this.D])));var b=this.w.getElementById(this.B);null===b&&x(z()).alert(M(N(new O,G(new H,["no elem with id ","!"])),G(new H,[this.B])));var c=20+k(70,this.Q)|0;a.setAttribute("visibility","hidden");b.setAttribute("transform",M(N(new O,G(new H,[" translate(0,",")"])),G(new H,[c])))};
d.F=function(a){switch(a){case 0:return this.D;case 1:return this.B;case 2:return this.Q;default:throw(new U).e(""+a);}};d.i=function(){return nd(this)};d.k=function(){var a=-889275714,a=A().M(a,Jc(A(),this.D)),a=A().M(a,Jc(A(),this.B)),a=A().M(a,this.Q);return A().ha(a,3)};d.N=function(){return W(this)};d.b=v({ac:0},!1,"presenter.FadeAndSlideDown",{ac:1,c:1,sb:1,H:1,j:1,f:1,d:1});function I(){this.Za=null}I.prototype=new w;I.prototype.constructor=I;d=I.prototype;d.G=function(){return"PanAndZoom"};
d.E=function(){return 1};d.F=function(a){switch(a){case 0:return this.Za;default:throw(new U).e(""+a);}};d.Da=function(){var a=xd(),b=this.Za,c=a.w.getElementById(b);null===c&&x(z()).alert(M(N(new O,G(new H,["no elem with id ","!"])),G(new H,[b])));a.Sa.setAttribute("viewBox",M(N(new O,G(new H,["0 0 "," ",""])),G(new H,[a.Qa,a.Pa])));b=c.getBoundingClientRect();a.Sa.setAttribute("viewBox",M(N(new O,G(new H,[""," "," "," ",""])),G(new H,[+b.left,+b.top,+b.width,+b.height])))};d.i=function(){return nd(this)};
d.e=function(a){this.Za=a;return this};d.k=function(){return Hc(this)};d.N=function(){return W(this)};d.b=v({bc:0},!1,"presenter.PanAndZoom",{bc:1,c:1,sb:1,H:1,j:1,f:1,d:1});function fe(){this.r=null}fe.prototype=new Se;fe.prototype.constructor=fe;fe.prototype.e=function(a){P.prototype.K.call(this,a);return this};fe.prototype.b=v({tc:0},!1,"java.lang.NumberFormatException",{tc:1,$a:1,Z:1,Y:1,L:1,c:1,d:1});function ef(){}ef.prototype=new We;ef.prototype.constructor=ef;d=ef.prototype;d.a=function(){return this};
d.G=function(){return"None"};d.E=function(){return 0};d.P=function(){return!0};d.zb=function(){throw(new V).e("None.get");};d.F=function(a){throw(new U).e(""+a);};d.i=function(){return"None"};d.k=function(){return 2433880};d.N=function(){return W(this)};d.b=v({Ac:0},!1,"scala.None$",{Ac:1,Bc:1,c:1,H:1,j:1,f:1,d:1});var ff=void 0;function Cc(){ff||(ff=(new ef).a());return ff}function Dc(){this.ea=null}Dc.prototype=new We;Dc.prototype.constructor=Dc;d=Dc.prototype;d.G=function(){return"Some"};d.E=function(){return 1};
d.P=function(){return!1};d.F=function(a){switch(a){case 0:return this.ea;default:throw(new U).e(""+a);}};d.zb=function(){return this.ea};d.i=function(){return nd(this)};d.wa=function(a){this.ea=a;return this};d.k=function(){return Hc(this)};d.N=function(){return W(this)};d.b=v({Gc:0},!1,"scala.Some",{Gc:1,Bc:1,c:1,H:1,j:1,f:1,d:1});function gf(){this.r=null}gf.prototype=new Se;gf.prototype.constructor=gf;
function Ye(a,b){var c=new gf,e=N(new O,G(new H,["invalid escape "," index ",' in "','". Use \\\\\\\\ for literal \\\\.']));ie||(ie=(new he).a());if(!(0<=b&&b<(a.length|0)))throw(new T).e("requirement failed");if(b===(-1+(a.length|0)|0))var g="at terminal";else var g=N(new O,G(new H,["'\\\\","' not one of "," at"])),m=65535&(a.charCodeAt(1+b|0)|0),g=M(g,G(new H,[Zd(m),"[\\b, \\t, \\n, \\f, \\r, \\\\, \\\", \\']"]));a=M(e,G(new H,[g,b,a]));P.prototype.K.call(c,a);return c}
gf.prototype.b=v({Jc:0},!1,"scala.StringContext$InvalidEscapeException",{Jc:1,$a:1,Z:1,Y:1,L:1,c:1,d:1});function hf(){this.vb=null}hf.prototype=new $e;hf.prototype.constructor=hf;d=hf.prototype;d.G=function(){return"Failure"};d.E=function(){return 1};d.F=function(a){switch(a){case 0:return this.vb;default:throw(new U).e(""+a);}};d.i=function(){return nd(this)};function Ad(a){var b=new hf;b.vb=a;return b}d.yb=function(a){return(0,a.ta)()};d.k=function(){return Hc(this)};d.N=function(){return W(this)};
d.b=v({ld:0},!1,"scala.util.Failure",{ld:1,pd:1,c:1,H:1,j:1,f:1,d:1});function zd(){this.ea=null}zd.prototype=new $e;zd.prototype.constructor=zd;d=zd.prototype;d.G=function(){return"Success"};d.E=function(){return 1};d.F=function(a){switch(a){case 0:return this.ea;default:throw(new U).e(""+a);}};d.i=function(){return nd(this)};d.wa=function(a){this.ea=a;return this};d.yb=function(){return this.ea};d.k=function(){return Hc(this)};d.N=function(){return W(this)};
d.b=v({od:0},!1,"scala.util.Success",{od:1,pd:1,c:1,H:1,j:1,f:1,d:1});
function jf(a){a=ia(a.Fb()).W.name;for(var b=-1+(a.length|0)|0;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;if(-1===b||46===(65535&(a.charCodeAt(b)|0)))return"";for(var c="";;){for(var e=1+b|0;;)if(-1!==b&&57>=(65535&(a.charCodeAt(b)|0))&&48<=(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;for(var g=b;;)if(-1!==b&&36!==(65535&(a.charCodeAt(b)|0))&&46!==(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var m=1+b|0;if(b===g&&e!==(a.length|0))return c;for(;;)if(-1!==b&&36===(65535&
(a.charCodeAt(b)|0)))b=-1+b|0;else break;var g=-1===b?!0:46===(65535&(a.charCodeAt(b)|0)),r;(r=g)||(r=65535&(a.charCodeAt(m)|0),r=!(90<r&&127>r||65>r));if(r){e=a.substring(m,e);m=c;if(null===m)throw(new Te).a();c=""===m?e:""+e+Zd(46)+c;if(g)return c}}}function kf(){}kf.prototype=new xe;kf.prototype.constructor=kf;function lf(){}lf.prototype=kf.prototype;function me(){}me.prototype=new cf;me.prototype.constructor=me;me.prototype.a=function(){return this};
me.prototype.b=v({Ud:0},!1,"scala.collection.immutable.Set$",{Ud:1,Ze:1,af:1,Xe:1,ca:1,c:1,da:1});var le=void 0;function fb(){}fb.prototype=new lf;fb.prototype.constructor=fb;fb.prototype.a=function(){Q.prototype.a.call(this);return this};fb.prototype.b=v({Gd:0},!1,"scala.collection.Seq$",{Gd:1,Oa:1,Na:1,ma:1,ca:1,c:1,na:1,da:1});var eb=void 0;function mf(){}mf.prototype=new lf;mf.prototype.constructor=mf;function nf(){}nf.prototype=mf.prototype;function of(){this.l=null}of.prototype=new w;
of.prototype.constructor=of;function X(){}X.prototype=of.prototype;of.prototype.i=function(){return this.l};of.prototype.k=function(){return xa(this)};function pf(){}pf.prototype=new w;pf.prototype.constructor=pf;function qf(){}qf.prototype=pf.prototype;function rf(){}rf.prototype=new nf;rf.prototype.constructor=rf;rf.prototype.a=function(){Q.prototype.a.call(this);sf=this;(new ve).a();return this};rf.prototype.b=v({zd:0},!1,"scala.collection.IndexedSeq$",{zd:1,Md:1,Oa:1,Na:1,ma:1,ca:1,c:1,na:1,da:1});
var sf=void 0;function gb(){sf||(sf=(new rf).a());return sf}function tf(){this.ja=this.Ya=0;this.za=null}tf.prototype=new Pe;tf.prototype.constructor=tf;tf.prototype.C=function(){this.ja>=this.Ya&&hb().Xa.C();var a=this.za.Ea(this.ja);this.ja=1+this.ja|0;return a};function td(a,b){var c=new tf;c.Ya=b;if(null===a)throw gd(kd(),null);c.za=a;c.ja=0;return c}tf.prototype.O=function(){return this.ja<this.Ya};
tf.prototype.b=v({Bd:0},!1,"scala.collection.IndexedSeqLike$Elements",{Bd:1,bb:1,c:1,gb:1,aa:1,$:1,Re:1,f:1,d:1});function id(){this.ga=this.r=null}id.prototype=new He;id.prototype.constructor=id;d=id.prototype;d.G=function(){return"JavaScriptException"};d.E=function(){return 1};d.Ga=function(){this.stackdata=this.ga;return this};d.F=function(a){switch(a){case 0:return this.ga;default:throw(new U).e(""+a);}};d.xb=function(){return ha(this.ga)};
d.wa=function(a){this.ga=a;P.prototype.K.call(this,null);return this};d.k=function(){return Hc(this)};d.N=function(){return W(this)};d.b=v({nb:0},!1,"scala.scalajs.js.JavaScriptException",{nb:1,Z:1,Y:1,L:1,c:1,d:1,H:1,j:1,f:1});function hc(){this.l=null}hc.prototype=new X;hc.prototype.constructor=hc;hc.prototype.a=function(){this.l="Boolean";return this};hc.prototype.b=v({Xc:0},!1,"scala.reflect.ManifestFactory$BooleanManifest$",{Xc:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var gc=void 0;
function Ub(){this.l=null}Ub.prototype=new X;Ub.prototype.constructor=Ub;Ub.prototype.a=function(){this.l="Byte";return this};Ub.prototype.b=v({Yc:0},!1,"scala.reflect.ManifestFactory$ByteManifest$",{Yc:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var Tb=void 0;function Yb(){this.l=null}Yb.prototype=new X;Yb.prototype.constructor=Yb;Yb.prototype.a=function(){this.l="Char";return this};Yb.prototype.b=v({Zc:0},!1,"scala.reflect.ManifestFactory$CharManifest$",{Zc:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});
var Xb=void 0;function fc(){this.l=null}fc.prototype=new X;fc.prototype.constructor=fc;fc.prototype.a=function(){this.l="Double";return this};fc.prototype.b=v({$c:0},!1,"scala.reflect.ManifestFactory$DoubleManifest$",{$c:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var ec=void 0;function dc(){this.l=null}dc.prototype=new X;dc.prototype.constructor=dc;dc.prototype.a=function(){this.l="Float";return this};
dc.prototype.b=v({ad:0},!1,"scala.reflect.ManifestFactory$FloatManifest$",{ad:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var cc=void 0;function $b(){this.l=null}$b.prototype=new X;$b.prototype.constructor=$b;$b.prototype.a=function(){this.l="Int";return this};$b.prototype.b=v({bd:0},!1,"scala.reflect.ManifestFactory$IntManifest$",{bd:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var Zb=void 0;function bc(){this.l=null}bc.prototype=new X;bc.prototype.constructor=bc;bc.prototype.a=function(){this.l="Long";return this};
bc.prototype.b=v({cd:0},!1,"scala.reflect.ManifestFactory$LongManifest$",{cd:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var ac=void 0;function uf(){this.I=null}uf.prototype=new qf;uf.prototype.constructor=uf;function wf(){}wf.prototype=uf.prototype;uf.prototype.i=function(){return this.I};uf.prototype.k=function(){return xa(this)};function Wb(){this.l=null}Wb.prototype=new X;Wb.prototype.constructor=Wb;Wb.prototype.a=function(){this.l="Short";return this};
Wb.prototype.b=v({gd:0},!1,"scala.reflect.ManifestFactory$ShortManifest$",{gd:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var Vb=void 0;function jc(){this.l=null}jc.prototype=new X;jc.prototype.constructor=jc;jc.prototype.a=function(){this.l="Unit";return this};jc.prototype.b=v({hd:0},!1,"scala.reflect.ManifestFactory$UnitManifest$",{hd:1,T:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var ic=void 0;function jb(){}jb.prototype=new lf;jb.prototype.constructor=jb;
jb.prototype.a=function(){Q.prototype.a.call(this);ib=this;(new R).a();return this};jb.prototype.b=v({Pd:0},!1,"scala.collection.immutable.List$",{Pd:1,Oa:1,Na:1,ma:1,ca:1,c:1,na:1,da:1,f:1,d:1});var ib=void 0;function sb(){}sb.prototype=new lf;sb.prototype.constructor=sb;sb.prototype.a=function(){Q.prototype.a.call(this);return this};sb.prototype.b=v({Vd:0},!1,"scala.collection.immutable.Stream$",{Vd:1,Oa:1,Na:1,ma:1,ca:1,c:1,na:1,da:1,f:1,d:1});var rb=void 0;function lc(){this.I=null}
lc.prototype=new wf;lc.prototype.constructor=lc;lc.prototype.a=function(){this.I="Any";Cc();kb();n(Da);return this};lc.prototype.b=v({Vc:0},!1,"scala.reflect.ManifestFactory$AnyManifest$",{Vc:1,La:1,Ka:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var kc=void 0;function pc(){this.I=null}pc.prototype=new wf;pc.prototype.constructor=pc;pc.prototype.a=function(){this.I="AnyVal";Cc();kb();n(Da);return this};
pc.prototype.b=v({Wc:0},!1,"scala.reflect.ManifestFactory$AnyValManifest$",{Wc:1,La:1,Ka:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var oc=void 0;function rc(){this.I=null}rc.prototype=new wf;rc.prototype.constructor=rc;rc.prototype.a=function(){this.I="Nothing";Cc();kb();n(Fe);return this};rc.prototype.b=v({dd:0},!1,"scala.reflect.ManifestFactory$NothingManifest$",{dd:1,La:1,Ka:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var qc=void 0;function tc(){this.I=null}tc.prototype=new wf;tc.prototype.constructor=tc;
tc.prototype.a=function(){this.I="Null";Cc();kb();n(ld);return this};tc.prototype.b=v({ed:0},!1,"scala.reflect.ManifestFactory$NullManifest$",{ed:1,La:1,Ka:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var sc=void 0;function nc(){this.I=null}nc.prototype=new wf;nc.prototype.constructor=nc;nc.prototype.a=function(){this.I="Object";Cc();kb();n(Da);return this};nc.prototype.b=v({fd:0},!1,"scala.reflect.ManifestFactory$ObjectManifest$",{fd:1,La:1,Ka:1,c:1,u:1,t:1,s:1,p:1,f:1,d:1,j:1});var mc=void 0;
function wb(){}wb.prototype=new nf;wb.prototype.constructor=wb;wb.prototype.a=function(){Q.prototype.a.call(this);vb=this;return this};wb.prototype.b=v({$d:0},!1,"scala.collection.immutable.Vector$",{$d:1,Md:1,Oa:1,Na:1,ma:1,ca:1,c:1,na:1,da:1,f:1,d:1});var vb=void 0;function Y(){}Y.prototype=new w;Y.prototype.constructor=Y;function xf(){}xf.prototype=Y.prototype;Y.prototype.Eb=function(a,b,c){return Oc(this,a,b,c)};Y.prototype.Ua=function(a,b,c,e){return Qc(this,a,b,c,e)};Y.prototype.Fb=function(){return this};
Y.prototype.Ra=function(){return jf(this)};function yf(a,b){for(var c=0,e=a.S();c<e;)b.J(a.Ea(c)),c=1+c|0}function zf(){}zf.prototype=new xf;zf.prototype.constructor=zf;function Af(){}Af.prototype=zf.prototype;zf.prototype.X=function(a){for(var b=this.xa();b.O();)a.J(b.C())};function L(){this.m=null}L.prototype=new w;L.prototype.constructor=L;d=L.prototype;d.Ea=function(a){a=65535&(this.m.charCodeAt(a)|0);return Zd(a)};d.Eb=function(a,b,c){return Oc(this,a,b,c)};d.i=function(){return this.m};
d.X=function(a){yf(this,a)};d.S=function(){return this.m.length|0};d.Ua=function(a,b,c,e){return Qc(this,a,b,c,e)};d.Fb=function(){return this.m};d.k=function(){var a=this.m;return ua(p(),a)};d.e=function(a){this.m=a;return this};d.Ra=function(){return jf(this)};d.b=v({Yd:0},!1,"scala.collection.immutable.StringOps",{Yd:1,c:1,Xd:1,Ob:1,Nb:1,ib:1,fb:1,j:1,jb:1,lb:1,kb:1,aa:1,$:1,eb:1,hb:1,cb:1,db:1,Oc:1,A:1});function Bf(){}Bf.prototype=new Af;Bf.prototype.constructor=Bf;function Cf(){}
Cf.prototype=Bf.prototype;Bf.prototype.i=function(){return this.Eb(this.Ra()+"(",", ",")")};function Df(){}Df.prototype=new Cf;Df.prototype.constructor=Df;function Ef(){}Ef.prototype=Df.prototype;function Ff(){}Ff.prototype=new Cf;Ff.prototype.constructor=Ff;function Gf(){}d=Gf.prototype=Ff.prototype;d.J=function(a){a|=0;for(var b=this,c=a;!b.P()&&0<c;)b=Kd(),c=-1+c|0;if(0>a||b.P())throw(new U).e(""+a);Jd()};d.X=function(a){for(var b=this;!b.P();)a.J(Hf()),b=Kd()};
d.xa=function(){var a=new af;a.ob=this;return a};d.S=function(){for(var a=this,b=0;!a.P();)b=1+b|0,a=Kd();return b};d.k=function(){return Id(this)};d.Ra=function(){return"List"};function If(){}If.prototype=new Gf;If.prototype.constructor=If;d=If.prototype;d.G=function(){return"Nil"};function Hf(){Jd()}d.a=function(){return this};d.E=function(){return 0};d.P=function(){return!0};function Kd(){throw(new Ue).e("tail of empty list");}d.F=function(a){throw(new U).e(""+a);};
function Jd(){throw(new V).e("head of empty list");}d.N=function(){return W(this)};d.b=v({Sd:0},!1,"scala.collection.immutable.Nil$",{Sd:1,Od:1,Ib:1,Hb:1,Jb:1,c:1,Rb:1,jb:1,lb:1,kb:1,aa:1,$:1,eb:1,hb:1,Mb:1,Tb:1,Pb:1,Kb:1,cb:1,fb:1,j:1,Qb:1,Gb:1,fa:1,Lb:1,db:1,ib:1,ef:1,ff:1,df:1,gf:1,Ie:1,Se:1,Te:1,H:1,Ue:1,f:1,d:1});var Jf=void 0;function kb(){Jf||(Jf=(new If).a())}function Kf(){}Kf.prototype=new Ef;Kf.prototype.constructor=Kf;function Lf(){}Lf.prototype=Kf.prototype;function Pc(){this.x=null}
Pc.prototype=new Ef;Pc.prototype.constructor=Pc;d=Pc.prototype;d.a=function(){Pc.prototype.fc.call(this,16,"");return this};d.Ea=function(a){a=65535&(this.x.o.charCodeAt(a)|0);return Zd(a)};d.J=function(a){a=65535&(this.x.o.charCodeAt(a|0)|0);return Zd(a)};d.Wb=function(a,b){return this.x.o.substring(a,b)};d.i=function(){return this.x.o};d.X=function(a){yf(this,a)};d.xa=function(){return td(this,this.x.o.length|0)};d.fc=function(a,b){Pc.prototype.gc.call(this,D((new S).ua((b.length|0)+a|0),b));return this};
d.S=function(){return this.x.o.length|0};d.gc=function(a){this.x=a;return this};function Sc(a,b){var c=a.x;p();D(c,null===b?"null":ha(b));return a}d.k=function(){return Id(this)};d.b=v({ie:0},!1,"scala.collection.mutable.StringBuilder",{ie:1,ae:1,Ib:1,Hb:1,Jb:1,c:1,Rb:1,jb:1,lb:1,kb:1,aa:1,$:1,eb:1,hb:1,Mb:1,Tb:1,Pb:1,Kb:1,cb:1,fb:1,j:1,Qb:1,Gb:1,fa:1,Lb:1,db:1,ib:1,ge:1,fe:1,ke:1,zc:1,he:1,ce:1,yc:1,Cb:1,Bb:1,de:1,yd:1,Nb:1,ee:1,Xd:1,Ob:1,Oc:1,A:1,nf:1,be:1,Ld:1,Id:1,f:1,d:1});
function H(){this.V=null}H.prototype=new Lf;H.prototype.constructor=H;d=H.prototype;d.Ea=function(a){return this.V[a]};d.J=function(a){return this.V[a|0]};d.X=function(a){yf(this,a)};d.xa=function(){return td(this,this.V.length|0)};d.S=function(){return this.V.length|0};d.k=function(){return Id(this)};function G(a,b){a.V=b;return a}d.Ra=function(){return"WrappedArray"};
d.b=v({le:0},!1,"scala.scalajs.js.WrappedArray",{le:1,hf:1,ae:1,Ib:1,Hb:1,Jb:1,c:1,Rb:1,jb:1,lb:1,kb:1,aa:1,$:1,eb:1,hb:1,Mb:1,Tb:1,Pb:1,Kb:1,cb:1,fb:1,j:1,Qb:1,Gb:1,fa:1,Lb:1,db:1,ib:1,ge:1,fe:1,ke:1,zc:1,he:1,ce:1,yc:1,Cb:1,kf:1,lf:1,Ld:1,Id:1,bf:1,Ve:1,cf:1,de:1,yd:1,Nb:1,ee:1,jf:1,mf:1,Ob:1,be:1});aa.presenter=aa.presenter||{};aa.presenter.Presentation=xd;
}).call(this);
//# sourceMappingURL=scaladays2014-opt.js.map
